modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "legendarium"
version = "24.07.19"
displayName = "Legendary Item"
authors = "Hummel009"
description = '''This mod adds legendary artifacts from the Lord of the Rings to Minecraft.'''

[[dependencies.legendarium]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legendarium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"