modLoader="javafml" 
loaderVersion="[3,)" 
license="Powered by Hummel009"

[[mods]]
modId="legendarium"
version="4.1"
displayName="Legendary Item"
logoFile="logo.png"
credits="Hummel009"
authors="Hummel009"
description='''This mod adds legendary artifacts from the Lord of the Rings to Minecraft'''
[[dependencies.legendarium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"