modLoader = "javafml"
loaderVersion = "[3,)"
license = "Powered by Hummel009"

[[mods]]
modId = "legendarium"
version = "23.06.07"
displayName = "Legendary Item"
logoFile = "logo.png"
credits = "Hummel009"
authors = "Hummel009"
description = '''This mod adds legendary artifacts from the Lord of the Rings to Minecraft'''
[[dependencies.legendarium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20]"
ordering = "NONE"
side = "BOTH"