# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build with Gradle
      working-directory: ./1.3.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.4.7
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.5.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.6.4
      run: ./gradlew.bat build
        
    - name: Setup Decomp Workspace
      working-directory: ./1.7.10
      run: ./gradlew.bat setupDecompWorkspace eclipse
        
    - name: Build with Gradle
      working-directory: ./1.7.10
      run: ./gradlew.bat build
        
    - name: Setup Decomp Workspace
      working-directory: ./1.8.9
      run: ./gradlew.bat setupDecompWorkspace eclipse
        
    - name: Build with Gradle
      working-directory: ./1.8.9
      run: ./gradlew.bat build
        
    - name: Setup Decomp Workspace
      working-directory: ./1.9.4
      run: ./gradlew.bat setupDecompWorkspace eclipse
        
    - name: Build with Gradle
      working-directory: ./1.9.4
      run: ./gradlew.bat build
        
    - name: Setup Decomp Workspace
      working-directory: ./1.10.2
      run: ./gradlew.bat setupDecompWorkspace eclipse
        
    - name: Build with Gradle
      working-directory: ./1.10.2
      run: ./gradlew.bat build
        
    - name: Setup Decomp Workspace
      working-directory: ./1.11.2
      run: ./gradlew.bat setupDecompWorkspace eclipse
        
    - name: Build with Gradle
      working-directory: ./1.11.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.12.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.13.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.14.4
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.15.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.16.5
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.17.1
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.18.2
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.19.4
      run: ./gradlew.bat build
        
    - name: Build with Gradle
      working-directory: ./1.20.1
      run: ./gradlew.bat build
