# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build1_3_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.3.2
      run: ./gradlew.bat build

  build1_4_7:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.4.7
      run: ./gradlew.bat build

  build1_5_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.5.2
      run: ./gradlew.bat build

  build1_6_4:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.6.4
      run: ./gradlew.bat build

  build1_7_10:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.7.10
      run: ./gradlew.bat build

  build1_8_9:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.8.9
      run: ./gradlew.bat build

  build1_9_4:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.9.4
      run: ./gradlew.bat build

  build1_10_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.10.2
      run: ./gradlew.bat build

  build1_11_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.11.2
      run: ./gradlew.bat build

  build1_12_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.12.2
      run: ./gradlew.bat build

  build1_13_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.13.2
      run: ./gradlew.bat build

  build1_14_4:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.14.4
      run: ./gradlew.bat build

  build1_15_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.15.2
      run: ./gradlew.bat build

  build1_16_5:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.16.5
      run: ./gradlew.bat build

  build1_17_1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.17.1
      run: ./gradlew.bat build

  build1_18_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.18.2
      run: ./gradlew.bat build

  build1_19_4:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.19.4
      run: ./gradlew.bat build

  build1_20_1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      working-directory: ./1.20.1
      run: ./gradlew.bat build
